//
//  Weather15Minutes.swift
//  IBMWeather
//
//  Created by Mac on 13.06.2020.
//  Copyright © 2020 Lammax. All rights reserved.
//

import Foundation

/*
{
   "metadata":{
      "language":"ru-RU",
      "transaction_id":"1592061107349:-195620913",
      "version":"1",
      "latitude":34.06,
      "longitude":-84.21,
      "units":"m",
      "expire_time_gmt":1592061707,
      "status_code":200
   },
   "forecasts":[
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592061300,
         "fcst_valid_local":"2020-06-13T11:15:00-0400",
         "num":1,
         "day_ind":"D",
         "temp":26,
         "dewpt":14,
         "hi":27,
         "wc":26,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":47,
         "wspd":11,
         "wdir":64,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":7,
         "gust":null,
         "clds":27,
         "vis":16.0,
         "mslp":1019.94,
         "uv_index_raw":6.88,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592062200,
         "fcst_valid_local":"2020-06-13T11:30:00-0400",
         "num":2,
         "day_ind":"D",
         "temp":26,
         "dewpt":14,
         "hi":27,
         "wc":26,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":46,
         "wspd":11,
         "wdir":64,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":7,
         "gust":null,
         "clds":25,
         "vis":16.0,
         "mslp":1019.89,
         "uv_index_raw":7.49,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592063100,
         "fcst_valid_local":"2020-06-13T11:45:00-0400",
         "num":3,
         "day_ind":"D",
         "temp":26,
         "dewpt":13,
         "hi":27,
         "wc":26,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":44,
         "wspd":12,
         "wdir":64,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":8,
         "gust":null,
         "clds":24,
         "vis":16.0,
         "mslp":1019.84,
         "uv_index_raw":8.07,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592064000,
         "fcst_valid_local":"2020-06-13T12:00:00-0400",
         "num":4,
         "day_ind":"D",
         "temp":27,
         "dewpt":13,
         "hi":27,
         "wc":27,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":43,
         "wspd":12,
         "wdir":64,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":9,
         "gust":null,
         "clds":22,
         "vis":16.0,
         "mslp":1019.79,
         "uv_index_raw":8.61,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592064900,
         "fcst_valid_local":"2020-06-13T12:15:00-0400",
         "num":5,
         "day_ind":"D",
         "temp":27,
         "dewpt":13,
         "hi":27,
         "wc":27,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":42,
         "wspd":12,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":9,
         "gust":null,
         "clds":24,
         "vis":16.0,
         "mslp":1019.72,
         "uv_index_raw":9.11,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592065800,
         "fcst_valid_local":"2020-06-13T12:30:00-0400",
         "num":6,
         "day_ind":"D",
         "temp":27,
         "dewpt":13,
         "hi":27,
         "wc":27,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":41,
         "wspd":11,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":25,
         "vis":16.0,
         "mslp":1019.64,
         "uv_index_raw":9.54,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592066700,
         "fcst_valid_local":"2020-06-13T12:45:00-0400",
         "num":7,
         "day_ind":"D",
         "temp":27,
         "dewpt":13,
         "hi":27,
         "wc":27,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":40,
         "wspd":11,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":26,
         "vis":16.0,
         "mslp":1019.57,
         "uv_index_raw":9.89,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592067600,
         "fcst_valid_local":"2020-06-13T13:00:00-0400",
         "num":8,
         "day_ind":"D",
         "temp":27,
         "dewpt":12,
         "hi":27,
         "wc":27,
         "feels_like":27,
         "icon_extd":3400,
         "wxman":"wx1000",
         "icon_code":34,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Преимущественно солнечно",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":39,
         "wspd":11,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":27,
         "vis":16.0,
         "mslp":1019.5,
         "uv_index_raw":10.17,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592068500,
         "fcst_valid_local":"2020-06-13T13:15:00-0400",
         "num":9,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":39,
         "wspd":11,
         "wdir":60,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":31,
         "vis":16.0,
         "mslp":1019.38,
         "uv_index_raw":10.35,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592069400,
         "fcst_valid_local":"2020-06-13T13:30:00-0400",
         "num":10,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":38,
         "wspd":11,
         "wdir":58,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":35,
         "vis":16.0,
         "mslp":1019.26,
         "uv_index_raw":10.44,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592070300,
         "fcst_valid_local":"2020-06-13T13:45:00-0400",
         "num":11,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":38,
         "wspd":10,
         "wdir":56,
         "wdir_cardinal":"СВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":38,
         "vis":16.0,
         "mslp":1019.14,
         "uv_index_raw":10.43,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592071200,
         "fcst_valid_local":"2020-06-13T14:00:00-0400",
         "num":12,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":38,
         "wspd":10,
         "wdir":54,
         "wdir_cardinal":"СВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":42,
         "vis":16.0,
         "mslp":1019.01,
         "uv_index_raw":10.34,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592072100,
         "fcst_valid_local":"2020-06-13T14:15:00-0400",
         "num":13,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":38,
         "wspd":10,
         "wdir":55,
         "wdir_cardinal":"СВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":41,
         "vis":16.0,
         "mslp":1018.86,
         "uv_index_raw":10.15,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592073000,
         "fcst_valid_local":"2020-06-13T14:30:00-0400",
         "num":14,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":38,
         "wspd":10,
         "wdir":57,
         "wdir_cardinal":"СВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":39,
         "vis":16.0,
         "mslp":1018.71,
         "uv_index_raw":9.87,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592073900,
         "fcst_valid_local":"2020-06-13T14:45:00-0400",
         "num":15,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":37,
         "wspd":10,
         "wdir":58,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":10,
         "gust":null,
         "clds":38,
         "vis":16.0,
         "mslp":1018.55,
         "uv_index_raw":9.5,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592074800,
         "fcst_valid_local":"2020-06-13T15:00:00-0400",
         "num":16,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":0,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":37,
         "wspd":10,
         "wdir":59,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":9,
         "gust":null,
         "clds":37,
         "vis":16.0,
         "mslp":1018.4,
         "uv_index_raw":9.06,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592075700,
         "fcst_valid_local":"2020-06-13T15:15:00-0400",
         "num":17,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":37,
         "wspd":10,
         "wdir":61,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":9,
         "gust":null,
         "clds":37,
         "vis":16.0,
         "mslp":1018.3,
         "uv_index_raw":8.57,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592076600,
         "fcst_valid_local":"2020-06-13T15:30:00-0400",
         "num":18,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":62,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Очень высокий",
         "uv_index":8,
         "gust":null,
         "clds":37,
         "vis":16.0,
         "mslp":1018.2,
         "uv_index_raw":8.02,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592077500,
         "fcst_valid_local":"2020-06-13T15:45:00-0400",
         "num":19,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":7,
         "gust":null,
         "clds":38,
         "vis":16.0,
         "mslp":1018.1,
         "uv_index_raw":7.43,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592078400,
         "fcst_valid_local":"2020-06-13T16:00:00-0400",
         "num":20,
         "day_ind":"D",
         "temp":29,
         "dewpt":12,
         "hi":29,
         "wc":29,
         "feels_like":29,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":2,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":9,
         "wdir":65,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":7,
         "gust":null,
         "clds":38,
         "vis":16.0,
         "mslp":1018.0,
         "uv_index_raw":6.82,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592079300,
         "fcst_valid_local":"2020-06-13T16:15:00-0400",
         "num":21,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":2,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":64,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":6,
         "gust":null,
         "clds":39,
         "vis":16.0,
         "mslp":1017.9,
         "uv_index_raw":6.2,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592080200,
         "fcst_valid_local":"2020-06-13T16:30:00-0400",
         "num":22,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Высокий",
         "uv_index":6,
         "gust":null,
         "clds":39,
         "vis":16.0,
         "mslp":1017.81,
         "uv_index_raw":5.57,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592081100,
         "fcst_valid_local":"2020-06-13T16:45:00-0400",
         "num":23,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":62,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Средний",
         "uv_index":5,
         "gust":null,
         "clds":40,
         "vis":16.0,
         "mslp":1017.71,
         "uv_index_raw":4.95,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592082000,
         "fcst_valid_local":"2020-06-13T17:00:00-0400",
         "num":24,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":11,
         "wdir":61,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Средний",
         "uv_index":4,
         "gust":null,
         "clds":41,
         "vis":16.0,
         "mslp":1017.61,
         "uv_index_raw":4.35,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592082900,
         "fcst_valid_local":"2020-06-13T17:15:00-0400",
         "num":25,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":2,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":62,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Средний",
         "uv_index":4,
         "gust":null,
         "clds":39,
         "vis":16.0,
         "mslp":1017.58,
         "uv_index_raw":3.76,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592083800,
         "fcst_valid_local":"2020-06-13T17:30:00-0400",
         "num":26,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":2,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":62,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Средний",
         "uv_index":3,
         "gust":null,
         "clds":38,
         "vis":16.0,
         "mslp":1017.55,
         "uv_index_raw":3.21,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592084700,
         "fcst_valid_local":"2020-06-13T17:45:00-0400",
         "num":27,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":36,
         "wspd":10,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Средний",
         "uv_index":3,
         "gust":null,
         "clds":36,
         "vis":16.0,
         "mslp":1017.52,
         "uv_index_raw":2.69,
         "uv_warning":0,
         "severity":1
      },
      {
         "class":"fod_short_range_fifteen_minute",
         "expire_time_gmt":1592061707,
         "fcst_valid":1592085600,
         "fcst_valid_local":"2020-06-13T18:00:00-0400",
         "num":28,
         "day_ind":"D",
         "temp":28,
         "dewpt":12,
         "hi":28,
         "wc":28,
         "feels_like":28,
         "icon_extd":3000,
         "wxman":"wx1100",
         "icon_code":30,
         "dow":"Суббота",
         "phrase_12char":"",
         "phrase_22char":"",
         "phrase_32char":"Переменная облачность",
         "subphrase_pt1":"",
         "subphrase_pt2":"",
         "subphrase_pt3":"",
         "pop":1,
         "precip_type":"rain",
         "precip_rate":0.0,
         "snow_rate":0.0,
         "rh":37,
         "wspd":10,
         "wdir":63,
         "wdir_cardinal":"ВСВ",
         "uv_desc":"Низкий",
         "uv_index":2,
         "gust":null,
         "clds":35,
         "vis":16.0,
         "mslp":1017.49,
         "uv_index_raw":2.21,
         "uv_warning":0,
         "severity":1
      }
   ]
}
*/

enum DayTime: String, Decodable {
    case day = "D"
    case night = "N"
    case missing = "X" //for extreme northern and southern hemisphere
}

struct Weather15Minutes: Decodable {
    let metadata: Metadata?
    let forecasts: [Weather15MinutesForecast]?
    
    init(metadata: Metadata? = nil, forecasts: [Weather15MinutesForecast]? = nil) {
        self.metadata = metadata
        self.forecasts = forecasts
    }
    
    static var placeholder: Weather15Minutes {
        Weather15Minutes(metadata: nil, forecasts: nil)
    }
}

/*
 {
    "class":"fod_short_range_fifteen_minute",
    "expire_time_gmt":1592061707,
    "fcst_valid":1592061300,
    "fcst_valid_local":"2020-06-13T11:15:00-0400",
    "icon_code":34,
    "num":1,
    "day_ind":"D",
    "temp":26,
    "dewpt":14,
    "hi":27,
    "wc":26,
    "feels_like":27,
    "icon_extd":3400,
    "wxman":"wx1000",
    "dow":"Суббота",
    "phrase_12char":"",
    "phrase_22char":"",
    "phrase_32char":"Преимущественно солнечно",
    "subphrase_pt1":"",
    "subphrase_pt2":"",
    "subphrase_pt3":"",
    "pop":0,
    "precip_type":"rain",
    "precip_rate":0.0,
    "snow_rate":0.0,
    "rh":47,
    "wspd":11,
    "wdir":64,
    "wdir_cardinal":"ВСВ",
    "uv_desc":"Высокий",
    "uv_index":7,
    "gust":null,
    "clds":27,
    "vis":16.0,
    "mslp":1019.94,
    "uv_index_raw":6.88,
    "uv_warning":0,
    "severity":1

 }
 */

struct Weather15MinutesForecast: Decodable {
    let classs: String?
    let expire_time_gmt: UInt? //Expiration time in UNIX seconds
    let fcst_valid: UInt? //Time forecast is valid in UNIX seconds
    let fcst_valid_local: String?
    let icon_code: Int?
    let num: Int?
    let day_ind: DayTime?
    let temp: Int? //Celsius or Fahrenheit: depends on units
    let dewpt: Int? //15 minute Dew point
    let hi: Int? //15 minute heat point
    let wc: Int? //15-minute minimum wind chill
    let feels_like: Int? //15-minute feels like temperature
    let icon_extd: Int? //extended weather icon code
    let wxman: String? //Code combining Hourly sensible weather and temperature conditions
    let dow: String? //Day of week
    let phrase_12char: String? //15-minute sensible weather phrase
    let phrase_22char: String? //15-minute sensible weather phrase
    let phrase_32char: String? //15-minute sensible weather phrase
    let subphrase_pt1: String? //Part 1 of 3-part 15-minute sensible weather phrase
    let subphrase_pt2: String? //Part 2 of 3-part 15-minute ssensible weather phrase
    let subphrase_pt3: String? //Part 3 of 3-part 15-minute sensible weather phrase
    let pop: Int? //15-minute maximum probability of precipitation
    let precip_type: PrecipType? //The short text describing the expected type accumulation associated with the Probability of Precipitation (POP) display for the 15-minute period.
    let precip_rate: Float? //The forecasted hourly precipitation rate calculated for the 15-minute period.  As this is a standard hourly rate, the approximate expected precipitation forecast for the 15-Minute period is the displayed valued divided by 4.
    let snow_rate: Float? //The forecasted hourly snow accumulation during the 15-minute period.  As this is a standard hourly rate, the approximate expected snowfall forecast for the 15-Minute period is the displayed valued divided by 4.
    let rh: Int? //The relative humidity of the air, which is defined as the ratio of the amount of water vapor in the air to the amount of vapor required to bring the air to saturation at a constant temperature. Relative humidity is always expressed as a percentage.
    let wspd: Int? //The maximum forecasted hourly wind speed for the 15-minute period.
    let wdir: Int? //Average wind direction in magnetic notation for the 15-minute period.
    let wdir_cardinal: String? //Average wind direction in cardinal notation for the 15-minute period.
    let uv_desc: String? //The UV Index Description which complements the UV Index value by providing an associated level of risk of skin damage due to exposure.
    let uv_index: Int? //Maximum UV index for the 15-minute period.
    let gust: Int? //The maximum expected wind gust speed.
    let clds: Int? //Average cloud cover expressed as a percentage for the 15-minute period.
    let vis: Float? //Prevailing hourly visibility
    let mslp: Float? //Mean sea level pressure
    let uv_index_raw: Float? //The non-truncated UV Index which is the intensity of the solar radiation based on a number of factors.
    let uv_warning: Int? //TWC-created UV warning based on UV index of 11 or greater.
    let severity: Int? //A code denoting how impactful is the forecasted weather for this 15-minute period. 0 (no threat) -> 6 dangerous (life threatening)


    enum CodingKeys: String, CodingKey {
        case classs = "class"
        case expire_time_gmt
        case fcst_valid
        case fcst_valid_local
        case icon_code
        case num
        case day_ind
        case temp
        case dewpt
        case hi
        case wc
        case feels_like
        case icon_extd
        case wxman
        case dow
        case phrase_12char
        case phrase_22char
        case phrase_32char
        case subphrase_pt1
        case subphrase_pt2
        case subphrase_pt3
        case pop
        case precip_type
        case precip_rate
        case snow_rate
        case rh
        case wspd
        case wdir
        case wdir_cardinal
        case uv_desc
        case uv_index
        case gust
        case clds
        case vis
        case mslp
        case uv_index_raw
        case uv_warning
        case severity

    }
}
